/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.fory.format.encoder;

import org.apache.fory.reflect.ReflectionUtils;

/**
 * Runtime entry point for row codecs generated by the {@code @ForyGenerate} annotation processor.
 * Resolves the generated {@code <Interface>_Fory} implementation without depending on the row-codec
 * code-generation machinery, so an application can run precompiled codecs with only {@code
 * fory-format-runtime} on its classpath.
 *
 * <p>Declare an {@code INSTANCE} constant on a {@code @ForyGenerate} interface that resolves
 * through this factory, so callers do not have to know the generated class name:
 *
 * <pre>{@code
 * @ForyGenerate
 * public interface MyCodecs {
 *   MyCodecs INSTANCE = RowCodecs.factory(MyCodecs.class);
 *
 *   byte[] encode(MyBean bean);
 *   MyBean decode(byte[] bytes);
 * }
 *
 * byte[] bytes = MyCodecs.INSTANCE.encode(new MyBean(...));
 * }</pre>
 */
public final class RowCodecs {

  private RowCodecs() {}

  /**
   * Return the singleton instance generated by {@code @ForyGenerate} for {@code ifaceClass}. The
   * generated class lives next to the interface as {@code <Interface>_Fory}; this helper derives
   * that name and returns its singleton so callers do not have to type the generated class name.
   *
   * <p>Loading goes through {@code ifaceClass}'s classloader, so the factory's static initializer
   * (including any {@code @ForyCustomCodec} / {@code @ForyCustomCollection} registrations the
   * processor echoed in) runs at the point of this call.
   *
   * @throws IllegalStateException if the generated factory is not on the classpath of {@code
   *     ifaceClass} — typically because the {@code @ForyGenerate} annotation processor has not been
   *     wired into the build that produced {@code ifaceClass}.
   */
  public static <T> T factory(Class<T> ifaceClass) {
    String binary = ifaceClass.getName();
    String pkg = ReflectionUtils.getPackage(ifaceClass);
    String simpleWithEnclosing = pkg.isEmpty() ? binary : binary.substring(pkg.length() + 1);
    String generated =
        (pkg.isEmpty() ? "" : pkg + ".") + simpleWithEnclosing.replace('$', '_') + "_Fory";
    Class<?> factoryClass;
    try {
      factoryClass = Class.forName(generated, true, ifaceClass.getClassLoader());
    } catch (ClassNotFoundException e) {
      throw new IllegalStateException(
          "Generated factory "
              + generated
              + " not found on the classloader of "
              + ifaceClass.getName()
              + ". Ensure the @ForyGenerate annotation processor is enabled for the build that "
              + "produces this interface.",
          e);
    }
    try {
      return ifaceClass.cast(factoryClass.getMethod("instance").invoke(null));
    } catch (ReflectiveOperationException e) {
      throw new IllegalStateException("Failed to invoke " + generated + ".instance()", e);
    }
  }
}
